language: ruby
rvm:
  - 2.0.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libreoffice
before_script:
  - psql -c 'create database tribunals_test;' -U postgres
services: postgres
script:
  - bundle exec rake db:migrate
  - bundle exec rake spec