development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: tribunals_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: tribunals_test
  pool: 5