utiac:
  filters:
  - name: 'reported'
    label: 'Case status'
    type: 'radio'
    options:
    - label: 'All'
      value: 'all'
      checked: true
    - label: 'Reported'
      value: 'reported'
    - label: 'Unreported'
      value: 'unreported'
  - name: 'country'
    label: 'Country'
    type: 'text'
    predictive: true
  sort_by:
  results_columns:

ftt-tax:
  filters:
  - name: 'judge'
    label: 'Name of judge'
    type: 'text'
    predictive: true
    placeholder: 'Show cases this judge heard only'
  - name: 'party'
    label: 'Name of party'
    type: 'text'
    predictive: true
    placeholder: 'Show cases brought by this party'
  - name: 'category'
    label: 'Topic'
    type: 'text'
    predictive: true
    placeholder: 'What the case is about'
  - name: 'subcategory'
    label: 'Sub-topic'
    type: 'text'
    predictive: true
    placeholder: 'More detail about the case'

  sort_by:
  - name: 'decision_date'
    label: 'Date of decision'
  - name: 'hearing_date'
    label: 'Date of hearing'
  results_columns:
  - name: 'reference_id'
    label: 'Reference number'
  - name: 'decision_date'
    label: 'Date of decision'

utaac:
  filters:
  - name: 'judge'
    label: 'Name of judge'
    type: 'text'
    predictive: true
    placeholder: 'Show cases this judge heard only'
  - name: 'party'
    label: 'Name of party'
    type: 'text'
    predictive: true
    placeholder: 'Show cases brought by this party'
  - name: 'category'
    label: 'Topic'
    type: 'text'
    predictive: true
    placeholder: 'What the case is about'
  - name: 'subcategory'
    label: 'Sub-topic'
    type: 'text'
    predictive: true
    placeholder: 'More detail about the case'
  sort_by:
  - name: 'created_at'
    label: 'Date added'
  - name: 'decision_date'
    label: 'Date of decision'
  results_columns:
  - name: 'reference_id' 
    label: 'Reference number'
  - name: 'decision_date' 
    label: 'Date of decision'

eat:
  filters:
  - name: 'judge'
    label: 'Name of judge'
    type: 'text'
    predictive: true
    placeholder: 'Show cases this judge heard only'
  - name: 'party'
    label: 'Name of party'
    type: 'text'
    predictive: true
    placeholder: 'Show cases brought by this party'
  - name: 'category'
    label: 'Topic'
    type: 'text'
    predictive: true
    placeholder: 'What the case is about'
  - name: 'subcategory'
    label: 'Sub-topic'
    type: 'text'
    predictive: true
    placeholder: 'More detail about the case'
  sort_by:
  form_fields:
    file_number: 'EAT number'
    starred: 'Starred judgement'
    claimant: 'Appellant Name'
    respondent: 'Respondent Name'
    all_judge: 'Judge Name'
    hearing_date: 'Date of hearing'
    upload_date: 'Date of upload'
    category: 'Topic'
    subcategory: 'Sub-topic'